/*
 * Redirect sys/fs/zfs.h to FreeBSD's actual zfs header location
 * OpenZFS headers expect Solaris-style path sys/fs/zfs.h
 * FreeBSD has it at different locations depending on the build
 */

#ifndef _SYS_FS_ZFS_H
#define _SYS_FS_ZFS_H

#include <sys/types.h>
#include <stdint.h>

/* Try common FreeBSD ZFS header locations */
#if __has_include(<sys/zfs_ioctl.h>)
#include <sys/zfs_ioctl.h>
#endif

/* ZFS property definitions */
#if __has_include(<sys/zfs_prop.h>)
#include <sys/zfs_prop.h>
#endif

/* If we still don't have the basics, provide minimal definitions */
#ifndef ZFS_MAX_DATASET_NAME_LEN
#define ZFS_MAX_DATASET_NAME_LEN 256
#endif

#ifndef MAXPATHLEN
#include <sys/param.h>
#endif

#ifndef MAXNAMELEN
#define MAXNAMELEN 256
#endif

/* ZFS dataset types - only define if not already defined */
#ifndef ZFS_TYPE_FILESYSTEM
#define ZFS_TYPE_FILESYSTEM     (1 << 0)
#define ZFS_TYPE_SNAPSHOT       (1 << 1)
#define ZFS_TYPE_VOLUME         (1 << 2)
#define ZFS_TYPE_POOL           (1 << 3)
#define ZFS_TYPE_BOOKMARK       (1 << 4)
#define ZFS_TYPE_DATASET        (ZFS_TYPE_FILESYSTEM | ZFS_TYPE_VOLUME | ZFS_TYPE_SNAPSHOT)
#endif

/* Type definitions that libzfs.h expects */
#ifndef _ZFS_TYPE_T
#define _ZFS_TYPE_T
typedef uint64_t zfs_type_t;
#endif

#ifndef _ZFS_PROP_T
#define _ZFS_PROP_T
typedef enum {
    ZFS_PROP_INVAL = -1,
    ZFS_PROP_TYPE,
    ZFS_PROP_CREATION,
    ZFS_PROP_USED,
    ZFS_PROP_AVAILABLE,
    ZFS_PROP_REFERENCED,
    ZFS_PROP_COMPRESSRATIO,
    ZFS_PROP_MOUNTED,
    ZFS_PROP_ORIGIN,
    ZFS_PROP_QUOTA,
    ZFS_PROP_RESERVATION,
    ZFS_PROP_VOLSIZE,
    ZFS_PROP_VOLBLOCKSIZE,
    ZFS_PROP_RECORDSIZE,
    ZFS_PROP_MOUNTPOINT,
    ZFS_PROP_SHARENFS,
    ZFS_PROP_CHECKSUM,
    ZFS_PROP_COMPRESSION,
    ZFS_PROP_ATIME,
    ZFS_PROP_DEVICES,
    ZFS_PROP_EXEC,
    ZFS_PROP_SETUID,
    ZFS_PROP_READONLY,
    ZFS_PROP_ZONED,
    ZFS_PROP_SNAPDIR,
    ZFS_PROP_ACLMODE,
    ZFS_PROP_ACLINHERIT,
    ZFS_PROP_CREATETXG,
    ZFS_PROP_NAME,
    ZFS_PROP_CANMOUNT,
    ZFS_PROP_ISCSIOPTIONS,
    ZFS_PROP_XATTR,
    ZFS_PROP_NUMCLONES,
    ZFS_PROP_COPIES,
    ZFS_PROP_VERSION,
    ZFS_PROP_UTF8ONLY,
    ZFS_PROP_NORMALIZE,
    ZFS_PROP_CASE,
    ZFS_PROP_VSCAN,
    ZFS_PROP_NBMAND,
    ZFS_PROP_SHARESMB,
    ZFS_PROP_REFQUOTA,
    ZFS_PROP_REFRESERVATION,
    ZFS_PROP_GUID,
    ZFS_PROP_PRIMARYCACHE,
    ZFS_PROP_SECONDARYCACHE,
    ZFS_PROP_USEDSNAP,
    ZFS_PROP_USEDDS,
    ZFS_PROP_USEDCHILD,
    ZFS_PROP_USEDREFRESERV,
    ZFS_PROP_USERACCOUNTING,
    ZFS_PROP_STMF_SHAREINFO,
    ZFS_PROP_DEFER_DESTROY,
    ZFS_PROP_USERREFS,
    ZFS_PROP_LOGBIAS,
    ZFS_PROP_UNIQUE,
    ZFS_PROP_OBJSETID,
    ZFS_PROP_DEDUP,
    ZFS_PROP_MLSLABEL,
    ZFS_PROP_SYNC,
    ZFS_PROP_REFRATIO,
    ZFS_PROP_WRITTEN,
    ZFS_PROP_CLONES,
    ZFS_PROP_LOGICALUSED,
    ZFS_PROP_LOGICALREFERENCED,
    ZFS_PROP_INCONSISTENT,
    ZFS_PROP_SNAPDEV,
    ZFS_PROP_ACLTYPE,
    ZFS_PROP_SELINUX_CONTEXT,
    ZFS_PROP_SELINUX_FSCONTEXT,
    ZFS_PROP_SELINUX_DEFCONTEXT,
    ZFS_PROP_SELINUX_ROOTCONTEXT,
    ZFS_PROP_RELATIME,
    ZFS_PROP_REDUNDANT_METADATA,
    ZFS_PROP_OVERLAY,
    ZFS_PROP_PREV_SNAP,
    ZFS_PROP_RECEIVE_RESUME_TOKEN,
    ZFS_NUM_PROPS
} zfs_prop_t;
#endif

#ifndef _ZPROP_FUNC
#define _ZPROP_FUNC
typedef int (*zprop_func)(int, void *);
#endif

#ifndef _VDEV_STATE_T
#define _VDEV_STATE_T
typedef enum vdev_state {
    VDEV_STATE_UNKNOWN = 0,
    VDEV_STATE_CLOSED,
    VDEV_STATE_OFFLINE,
    VDEV_STATE_REMOVED,
    VDEV_STATE_CANT_OPEN,
    VDEV_STATE_FAULTED,
    VDEV_STATE_DEGRADED,
    VDEV_STATE_HEALTHY
} vdev_state_t;
#endif

#ifndef _VDEV_AUX_T
#define _VDEV_AUX_T
typedef enum vdev_aux {
    VDEV_AUX_NONE = 0,
    VDEV_AUX_OPEN_FAILED,
    VDEV_AUX_CORRUPT_DATA,
    VDEV_AUX_NO_REPLICAS,
    VDEV_AUX_BAD_GUID_SUM,
    VDEV_AUX_TOO_SMALL,
    VDEV_AUX_BAD_LABEL,
    VDEV_AUX_VERSION_NEWER,
    VDEV_AUX_VERSION_OLDER,
    VDEV_AUX_UNSUP_FEAT,
    VDEV_AUX_SPARED,
    VDEV_AUX_ERR_EXCEEDED,
    VDEV_AUX_IO_FAILURE,
    VDEV_AUX_BAD_LOG,
    VDEV_AUX_EXTERNAL,
    VDEV_AUX_SPLIT_POOL,
    VDEV_AUX_CHILDREN_OFFLINE
} vdev_aux_t;
#endif

#ifndef _POOL_STATE_T
#define _POOL_STATE_T
typedef enum pool_state {
    POOL_STATE_ACTIVE = 0,
    POOL_STATE_EXPORTED,
    POOL_STATE_DESTROYED,
    POOL_STATE_SPARE,
    POOL_STATE_L2CACHE,
    POOL_STATE_UNINITIALIZED,
    POOL_STATE_UNAVAIL,
    POOL_STATE_POTENTIALLY_ACTIVE
} pool_state_t;
#endif

#ifndef _ZPOOL_PROP_T
#define _ZPOOL_PROP_T
typedef enum {
    ZPOOL_PROP_INVAL = -1,
    ZPOOL_PROP_NAME,
    ZPOOL_PROP_SIZE,
    ZPOOL_PROP_CAPACITY,
    ZPOOL_PROP_ALTROOT,
    ZPOOL_PROP_HEALTH,
    ZPOOL_PROP_GUID,
    ZPOOL_PROP_VERSION,
    ZPOOL_PROP_BOOTFS,
    ZPOOL_PROP_DELEGATION,
    ZPOOL_PROP_AUTOREPLACE,
    ZPOOL_PROP_CACHEFILE,
    ZPOOL_PROP_FAILUREMODE,
    ZPOOL_PROP_LISTSNAPS,
    ZPOOL_PROP_AUTOEXPAND,
    ZPOOL_PROP_DEDUPDITTO,
    ZPOOL_PROP_DEDUPRATIO,
    ZPOOL_PROP_FREE,
    ZPOOL_PROP_ALLOCATED,
    ZPOOL_PROP_READONLY,
    ZPOOL_PROP_ASHIFT,
    ZPOOL_PROP_COMMENT,
    ZPOOL_PROP_EXPANDSZ,
    ZPOOL_PROP_FREEING,
    ZPOOL_NUM_PROPS
} zpool_prop_t;
#endif

#ifndef _VDEV_PROP_T
#define _VDEV_PROP_T
typedef enum {
    VDEV_PROP_INVAL = -1,
    VDEV_PROP_USERPROP = VDEV_PROP_INVAL,
    VDEV_PROP_NAME,
    VDEV_PROP_CAPACITY,
    VDEV_PROP_STATE,
    VDEV_NUM_PROPS
} vdev_prop_t;
#endif

#ifndef _ZPROP_SOURCE_T
#define _ZPROP_SOURCE_T
typedef enum {
    ZPROP_SRC_NONE = 0x1,
    ZPROP_SRC_DEFAULT = 0x2,
    ZPROP_SRC_TEMPORARY = 0x4,
    ZPROP_SRC_LOCAL = 0x8,
    ZPROP_SRC_INHERITED = 0x10,
    ZPROP_SRC_RECEIVED = 0x20
} zprop_source_t;
#endif

#ifndef _POOL_TRIM_FUNC_T
#define _POOL_TRIM_FUNC_T
typedef enum {
    POOL_TRIM_START,
    POOL_TRIM_CANCEL,
    POOL_TRIM_SUSPEND,
    POOL_TRIM_FUNCS
} pool_trim_func_t;
#endif

#ifndef _POOL_INITIALIZE_FUNC_T
#define _POOL_INITIALIZE_FUNC_T
typedef enum {
    POOL_INITIALIZE_START,
    POOL_INITIALIZE_CANCEL,
    POOL_INITIALIZE_SUSPEND,
    POOL_INITIALIZE_FUNCS
} pool_initialize_func_t;
#endif

#ifndef _ZPOOL_ERRATA_T
#define _ZPOOL_ERRATA_T
typedef enum {
    ZPOOL_ERRATA_NONE,
    ZPOOL_ERRATA_ZOL_2094_SCRUB,
    ZPOOL_ERRATA_ZOL_2094_ASYNC_DESTROY,
    ZPOOL_ERRATA_ZOL_6845_ENCRYPTION,
    ZPOOL_ERRATA_ZOL_8308_ENCRYPTION
} zpool_errata_t;
#endif

/* zfs_ioc_t type for libzfs_core.h */
#ifndef _ZFS_IOC_T
#define _ZFS_IOC_T
typedef enum {
    ZFS_IOC_POOL_CREATE = 0,
    ZFS_IOC_POOL_DESTROY,
    ZFS_IOC_POOL_IMPORT,
    ZFS_IOC_POOL_EXPORT,
    ZFS_IOC_POOL_CONFIGS,
    ZFS_IOC_POOL_STATS,
    ZFS_IOC_POOL_TRYIMPORT,
    ZFS_IOC_POOL_SCAN,
    ZFS_IOC_POOL_FREEZE,
    ZFS_IOC_POOL_UPGRADE,
    ZFS_IOC_POOL_GET_HISTORY,
    ZFS_IOC_VDEV_ADD,
    ZFS_IOC_VDEV_REMOVE,
    ZFS_IOC_VDEV_SET_STATE,
    ZFS_IOC_VDEV_ATTACH,
    ZFS_IOC_VDEV_DETACH,
    ZFS_IOC_VDEV_SETPATH,
    ZFS_IOC_VDEV_SETFRU,
    ZFS_IOC_OBJSET_STATS,
    ZFS_IOC_OBJSET_ZPLPROPS,
    ZFS_IOC_DATASET_LIST_NEXT,
    ZFS_IOC_SNAPSHOT_LIST_NEXT,
    ZFS_IOC_SET_PROP,
    ZFS_IOC_CREATE,
    ZFS_IOC_DESTROY,
    ZFS_IOC_ROLLBACK,
    ZFS_IOC_RENAME,
    ZFS_IOC_RECV,
    ZFS_IOC_SEND,
    ZFS_IOC_INJECT_FAULT,
    ZFS_IOC_CLEAR_FAULT,
    ZFS_IOC_INJECT_LIST_NEXT,
    ZFS_IOC_ERROR_LOG,
    ZFS_IOC_CLEAR,
    ZFS_IOC_PROMOTE,
    ZFS_IOC_SNAPSHOT,
    ZFS_IOC_DSOBJ_TO_DSNAME,
    ZFS_IOC_OBJ_TO_PATH,
    ZFS_IOC_POOL_SET_PROPS,
    ZFS_IOC_POOL_GET_PROPS,
    ZFS_IOC_SET_FSACL,
    ZFS_IOC_GET_FSACL,
    ZFS_IOC_SHARE,
    ZFS_IOC_INHERIT_PROP,
    ZFS_IOC_SMB_ACL,
    ZFS_IOC_USERSPACE_ONE,
    ZFS_IOC_USERSPACE_MANY,
    ZFS_IOC_USERSPACE_UPGRADE,
    ZFS_IOC_HOLD,
    ZFS_IOC_RELEASE,
    ZFS_IOC_GET_HOLDS,
    ZFS_IOC_OBJSET_RECVD_PROPS,
    ZFS_IOC_VDEV_SPLIT,
    ZFS_IOC_NEXT_OBJ,
    ZFS_IOC_DIFF,
    ZFS_IOC_TMP_SNAPSHOT,
    ZFS_IOC_OBJ_TO_STATS,
    ZFS_IOC_SPACE_WRITTEN,
    ZFS_IOC_SPACE_SNAPS,
    ZFS_IOC_DESTROY_SNAPS,
    ZFS_IOC_POOL_REGUID,
    ZFS_IOC_POOL_REOPEN,
    ZFS_IOC_SEND_PROGRESS,
    ZFS_IOC_LOG_HISTORY,
    ZFS_IOC_SEND_NEW,
    ZFS_IOC_SEND_SPACE,
    ZFS_IOC_CLONE,
    ZFS_IOC_BOOKMARK,
    ZFS_IOC_GET_BOOKMARKS,
    ZFS_IOC_DESTROY_BOOKMARKS
} zfs_ioc_t;
#endif

#endif /* _SYS_FS_ZFS_H */
