const std = @import("std");

/// Shell types for completion generation
pub const Shell = enum {
    bash,
    zsh,
    fish,

    pub fn fromString(s: []const u8) ?Shell {
        if (std.mem.eql(u8, s, "bash")) return .bash;
        if (std.mem.eql(u8, s, "zsh")) return .zsh;
        if (std.mem.eql(u8, s, "fish")) return .fish;
        return null;
    }
};

/// Generate shell completion script
pub fn generate(shell: Shell, writer: anytype) !void {
    switch (shell) {
        .bash => try generateBash(writer),
        .zsh => try generateZsh(writer),
        .fish => try generateFish(writer),
    }
}

/// Generate Bash completion script
fn generateBash(writer: anytype) !void {
    try writer.writeAll(
        \\# Bash completion for axiom
        \\# Generated by: axiom completions bash
        \\
        \\_axiom_completions() {
        \\    local cur prev commands
        \\    cur="${COMP_WORDS[COMP_CWORD]}"
        \\    prev="${COMP_WORDS[COMP_CWORD-1]}"
        \\
        \\    # All available commands
        \\    commands="help version profile profile-create profile-show profile-update profile-delete install remove search info list resolve realize activate env env-destroy gc build import key key-add key-remove key-trust key-generate sign verify cache cache-add cache-remove cache-fetch cache-push cache-sync cache-clean completions user user-profile-create user-profile-show user-profile-update user-profile-delete user-resolve user-realize user-activate user-env user-env-destroy system-import system-gc system-users system-user-remove virtual virtual-list virtual-providers provides conflicts replaces"
        \\
        \\    case "${prev}" in
        \\        axiom)
        \\            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        profile-show|profile-update|profile-delete|resolve)
        \\            # Complete with profile names
        \\            local profiles=$(axiom profile --names-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${profiles}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        realize)
        \\            # First arg: env name, second arg: profile name
        \\            if [[ ${COMP_CWORD} -eq 3 ]]; then
        \\                local profiles=$(axiom profile --names-only 2>/dev/null)
        \\                COMPREPLY=($(compgen -W "${profiles}" -- "${cur}"))
        \\            fi
        \\            return 0
        \\            ;;
        \\        activate|env-destroy)
        \\            # Complete with environment names
        \\            local envs=$(axiom env --names-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${envs}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        install|remove|info)
        \\            # Complete with package names
        \\            local packages=$(axiom list --names-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${packages}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        key-remove|key-trust)
        \\            # Complete with key IDs
        \\            local keys=$(axiom key --ids-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${keys}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        cache-remove)
        \\            # Complete with cache URLs
        \\            local caches=$(axiom cache --urls-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${caches}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        gc)
        \\            COMPREPLY=($(compgen -W "--dry-run --force" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        import|sign|verify|key-add|build)
        \\            # Complete with files
        \\            COMPREPLY=($(compgen -f -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        completions)
        \\            COMPREPLY=($(compgen -W "bash zsh fish" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        user-profile-show|user-profile-update|user-profile-delete|user-resolve)
        \\            # Complete with user profile names
        \\            local profiles=$(axiom user --names-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${profiles}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        user-realize)
        \\            # First arg: env name, second arg: profile name
        \\            if [[ ${COMP_CWORD} -eq 3 ]]; then
        \\                local profiles=$(axiom user --names-only 2>/dev/null)
        \\                COMPREPLY=($(compgen -W "${profiles}" -- "${cur}"))
        \\            fi
        \\            return 0
        \\            ;;
        \\        user-activate|user-env-destroy)
        \\            # Complete with user environment names
        \\            local envs=$(axiom user-env --names-only 2>/dev/null)
        \\            COMPREPLY=($(compgen -W "${envs}" -- "${cur}"))
        \\            return 0
        \\            ;;
        \\        *)
        \\            ;;
        \\    esac
        \\
        \\    # Handle options
        \\    if [[ "${cur}" == -* ]]; then
        \\        case "${COMP_WORDS[1]}" in
        \\            cache-fetch)
        \\                COMPREPLY=($(compgen -W "--no-verify --install" -- "${cur}"))
        \\                ;;
        \\            cache-clean)
        \\                COMPREPLY=($(compgen -W "--force -f" -- "${cur}"))
        \\                ;;
        \\            sign)
        \\                COMPREPLY=($(compgen -W "--key" -- "${cur}"))
        \\                ;;
        \\            build)
        \\                COMPREPLY=($(compgen -W "--jobs --no-test --dry-run --keep-sandbox --no-import --verbose" -- "${cur}"))
        \\                ;;
        \\            *)
        \\                COMPREPLY=()
        \\                ;;
        \\        esac
        \\        return 0
        \\    fi
        \\}
        \\
        \\complete -F _axiom_completions axiom
        \\
    );
}

/// Generate Zsh completion script
fn generateZsh(writer: anytype) !void {
    try writer.writeAll(
        \\#compdef axiom
        \\# Zsh completion for axiom
        \\# Generated by: axiom completions zsh
        \\
        \\_axiom() {
        \\    local -a commands
        \\    commands=(
        \\        'help:Show help message'
        \\        'version:Show version information'
        \\        'profile:List profiles'
        \\        'profile-create:Create a new profile'
        \\        'profile-show:Show profile details'
        \\        'profile-update:Update a profile'
        \\        'profile-delete:Delete a profile'
        \\        'install:Add package to profile'
        \\        'remove:Remove package from profile'
        \\        'search:Search for packages'
        \\        'info:Show package information'
        \\        'list:List installed packages'
        \\        'resolve:Resolve profile dependencies'
        \\        'realize:Create environment from profile'
        \\        'activate:Activate an environment'
        \\        'env:List environments'
        \\        'env-destroy:Destroy an environment'
        \\        'gc:Run garbage collector'
        \\        'build:Build package from recipe'
        \\        'import:Import package into store'
        \\        'key:List trusted keys'
        \\        'key-add:Add public key'
        \\        'key-remove:Remove a key'
        \\        'key-trust:Mark key as trusted'
        \\        'key-generate:Generate new key pair'
        \\        'sign:Sign a package'
        \\        'verify:Verify package signature'
        \\        'cache:List configured caches'
        \\        'cache-add:Add a remote cache'
        \\        'cache-remove:Remove a remote cache'
        \\        'cache-fetch:Fetch package from cache'
        \\        'cache-push:Push package to cache'
        \\        'cache-sync:Sync with remote caches'
        \\        'cache-clean:Clean local cache'
        \\        'completions:Generate shell completions'
        \\        'user:List user profiles'
        \\        'user-profile-create:Create user profile'
        \\        'user-profile-show:Show user profile details'
        \\        'user-profile-update:Update user profile'
        \\        'user-profile-delete:Delete user profile'
        \\        'user-resolve:Resolve user profile dependencies'
        \\        'user-realize:Create user environment from profile'
        \\        'user-activate:Activate user environment'
        \\        'user-env:List user environments'
        \\        'user-env-destroy:Destroy user environment'
        \\        'system-import:Import package to system store (root)'
        \\        'system-gc:Run system garbage collector (root)'
        \\        'system-users:List all Axiom users (root)'
        \\        'system-user-remove:Remove user Axiom data (root)'
        \\        'virtual:List all virtual packages'
        \\        'virtual-list:List all virtual packages'
        \\        'virtual-providers:List packages providing a virtual package'
        \\        'provides:Show virtual packages a package provides'
        \\        'conflicts:Show packages that conflict with a package'
        \\        'replaces:Show packages that a package replaces'
        \\    )
        \\
        \\    _arguments -C \
        \\        '1: :->command' \
        \\        '*: :->args'
        \\
        \\    case $state in
        \\        command)
        \\            _describe 'command' commands
        \\            ;;
        \\        args)
        \\            case $words[2] in
        \\                profile-show|profile-update|profile-delete|resolve)
        \\                    _axiom_profiles
        \\                    ;;
        \\                activate|env-destroy)
        \\                    _axiom_environments
        \\                    ;;
        \\                install|remove|info)
        \\                    _axiom_packages
        \\                    ;;
        \\                key-remove|key-trust)
        \\                    _axiom_keys
        \\                    ;;
        \\                cache-remove)
        \\                    _axiom_caches
        \\                    ;;
        \\                import|sign|verify|key-add|build)
        \\                    _files
        \\                    ;;
        \\                completions)
        \\                    _values 'shell' bash zsh fish
        \\                    ;;
        \\                gc)
        \\                    _arguments '--dry-run[Show what would be collected]' '--force[Force collection]'
        \\                    ;;
        \\                cache-fetch)
        \\                    _arguments '--no-verify[Skip signature verification]' '--install[Install after fetch]'
        \\                    ;;
        \\                cache-clean)
        \\                    _arguments '(-f --force)'{-f,--force}'[Force cleanup]'
        \\                    ;;
        \\                build)
        \\                    _arguments \
        \\                        '--jobs[Number of parallel jobs]:jobs' \
        \\                        '--no-test[Skip test phase]' \
        \\                        '--dry-run[Show build plan only]' \
        \\                        '--keep-sandbox[Keep sandbox after build]' \
        \\                        '--no-import[Do not import result]' \
        \\                        '--verbose[Show detailed output]'
        \\                    ;;
        \\                user-profile-show|user-profile-update|user-profile-delete|user-resolve)
        \\                    _axiom_user_profiles
        \\                    ;;
        \\                user-activate|user-env-destroy)
        \\                    _axiom_user_environments
        \\                    ;;
        \\            esac
        \\            ;;
        \\    esac
        \\}
        \\
        \\_axiom_profiles() {
        \\    local -a profiles
        \\    profiles=(${(f)"$(axiom profile --names-only 2>/dev/null)"})
        \\    _describe 'profile' profiles
        \\}
        \\
        \\_axiom_environments() {
        \\    local -a envs
        \\    envs=(${(f)"$(axiom env --names-only 2>/dev/null)"})
        \\    _describe 'environment' envs
        \\}
        \\
        \\_axiom_packages() {
        \\    local -a packages
        \\    packages=(${(f)"$(axiom list --names-only 2>/dev/null)"})
        \\    _describe 'package' packages
        \\}
        \\
        \\_axiom_keys() {
        \\    local -a keys
        \\    keys=(${(f)"$(axiom key --ids-only 2>/dev/null)"})
        \\    _describe 'key' keys
        \\}
        \\
        \\_axiom_caches() {
        \\    local -a caches
        \\    caches=(${(f)"$(axiom cache --urls-only 2>/dev/null)"})
        \\    _describe 'cache' caches
        \\}
        \\
        \\_axiom_user_profiles() {
        \\    local -a profiles
        \\    profiles=(${(f)"$(axiom user --names-only 2>/dev/null)"})
        \\    _describe 'user profile' profiles
        \\}
        \\
        \\_axiom_user_environments() {
        \\    local -a envs
        \\    envs=(${(f)"$(axiom user-env --names-only 2>/dev/null)"})
        \\    _describe 'user environment' envs
        \\}
        \\
        \\_axiom
        \\
    );
}

/// Generate Fish completion script
fn generateFish(writer: anytype) !void {
    try writer.writeAll(
        \\# Fish completion for axiom
        \\# Generated by: axiom completions fish
        \\
        \\# Disable file completion by default
        \\complete -c axiom -f
        \\
        \\# Helper functions for dynamic completion
        \\function __axiom_profiles
        \\    axiom profile --names-only 2>/dev/null
        \\end
        \\
        \\function __axiom_environments
        \\    axiom env --names-only 2>/dev/null
        \\end
        \\
        \\function __axiom_packages
        \\    axiom list --names-only 2>/dev/null
        \\end
        \\
        \\function __axiom_keys
        \\    axiom key --ids-only 2>/dev/null
        \\end
        \\
        \\function __axiom_caches
        \\    axiom cache --urls-only 2>/dev/null
        \\end
        \\
        \\function __axiom_user_profiles
        \\    axiom user --names-only 2>/dev/null
        \\end
        \\
        \\function __axiom_user_environments
        \\    axiom user-env --names-only 2>/dev/null
        \\end
        \\
        \\# Commands
        \\complete -c axiom -n __fish_use_subcommand -a help -d 'Show help message'
        \\complete -c axiom -n __fish_use_subcommand -a version -d 'Show version information'
        \\complete -c axiom -n __fish_use_subcommand -a profile -d 'List profiles'
        \\complete -c axiom -n __fish_use_subcommand -a profile-create -d 'Create a new profile'
        \\complete -c axiom -n __fish_use_subcommand -a profile-show -d 'Show profile details'
        \\complete -c axiom -n __fish_use_subcommand -a profile-update -d 'Update a profile'
        \\complete -c axiom -n __fish_use_subcommand -a profile-delete -d 'Delete a profile'
        \\complete -c axiom -n __fish_use_subcommand -a install -d 'Add package to profile'
        \\complete -c axiom -n __fish_use_subcommand -a remove -d 'Remove package from profile'
        \\complete -c axiom -n __fish_use_subcommand -a search -d 'Search for packages'
        \\complete -c axiom -n __fish_use_subcommand -a info -d 'Show package information'
        \\complete -c axiom -n __fish_use_subcommand -a list -d 'List installed packages'
        \\complete -c axiom -n __fish_use_subcommand -a resolve -d 'Resolve profile dependencies'
        \\complete -c axiom -n __fish_use_subcommand -a realize -d 'Create environment from profile'
        \\complete -c axiom -n __fish_use_subcommand -a activate -d 'Activate an environment'
        \\complete -c axiom -n __fish_use_subcommand -a env -d 'List environments'
        \\complete -c axiom -n __fish_use_subcommand -a env-destroy -d 'Destroy an environment'
        \\complete -c axiom -n __fish_use_subcommand -a gc -d 'Run garbage collector'
        \\complete -c axiom -n __fish_use_subcommand -a build -d 'Build package from recipe'
        \\complete -c axiom -n __fish_use_subcommand -a import -d 'Import package into store'
        \\complete -c axiom -n __fish_use_subcommand -a key -d 'List trusted keys'
        \\complete -c axiom -n __fish_use_subcommand -a key-add -d 'Add public key'
        \\complete -c axiom -n __fish_use_subcommand -a key-remove -d 'Remove a key'
        \\complete -c axiom -n __fish_use_subcommand -a key-trust -d 'Mark key as trusted'
        \\complete -c axiom -n __fish_use_subcommand -a key-generate -d 'Generate new key pair'
        \\complete -c axiom -n __fish_use_subcommand -a sign -d 'Sign a package'
        \\complete -c axiom -n __fish_use_subcommand -a verify -d 'Verify package signature'
        \\complete -c axiom -n __fish_use_subcommand -a cache -d 'List configured caches'
        \\complete -c axiom -n __fish_use_subcommand -a cache-add -d 'Add a remote cache'
        \\complete -c axiom -n __fish_use_subcommand -a cache-remove -d 'Remove a remote cache'
        \\complete -c axiom -n __fish_use_subcommand -a cache-fetch -d 'Fetch package from cache'
        \\complete -c axiom -n __fish_use_subcommand -a cache-push -d 'Push package to cache'
        \\complete -c axiom -n __fish_use_subcommand -a cache-sync -d 'Sync with remote caches'
        \\complete -c axiom -n __fish_use_subcommand -a cache-clean -d 'Clean local cache'
        \\complete -c axiom -n __fish_use_subcommand -a completions -d 'Generate shell completions'
        \\complete -c axiom -n __fish_use_subcommand -a user -d 'List user profiles'
        \\complete -c axiom -n __fish_use_subcommand -a user-profile-create -d 'Create user profile'
        \\complete -c axiom -n __fish_use_subcommand -a user-profile-show -d 'Show user profile details'
        \\complete -c axiom -n __fish_use_subcommand -a user-profile-update -d 'Update user profile'
        \\complete -c axiom -n __fish_use_subcommand -a user-profile-delete -d 'Delete user profile'
        \\complete -c axiom -n __fish_use_subcommand -a user-resolve -d 'Resolve user profile dependencies'
        \\complete -c axiom -n __fish_use_subcommand -a user-realize -d 'Create user environment from profile'
        \\complete -c axiom -n __fish_use_subcommand -a user-activate -d 'Activate user environment'
        \\complete -c axiom -n __fish_use_subcommand -a user-env -d 'List user environments'
        \\complete -c axiom -n __fish_use_subcommand -a user-env-destroy -d 'Destroy user environment'
        \\complete -c axiom -n __fish_use_subcommand -a system-import -d 'Import package to system store (root)'
        \\complete -c axiom -n __fish_use_subcommand -a system-gc -d 'Run system garbage collector (root)'
        \\complete -c axiom -n __fish_use_subcommand -a system-users -d 'List all Axiom users (root)'
        \\complete -c axiom -n __fish_use_subcommand -a system-user-remove -d 'Remove user Axiom data (root)'
        \\complete -c axiom -n __fish_use_subcommand -a virtual -d 'List all virtual packages'
        \\complete -c axiom -n __fish_use_subcommand -a virtual-list -d 'List all virtual packages'
        \\complete -c axiom -n __fish_use_subcommand -a virtual-providers -d 'List packages providing virtual pkg'
        \\complete -c axiom -n __fish_use_subcommand -a provides -d 'Show virtual packages a package provides'
        \\complete -c axiom -n __fish_use_subcommand -a conflicts -d 'Show packages that conflict with a package'
        \\complete -c axiom -n __fish_use_subcommand -a replaces -d 'Show packages that a package replaces'
        \\
        \\# Profile commands - complete with profile names
        \\complete -c axiom -n '__fish_seen_subcommand_from profile-show profile-update profile-delete resolve' -a '(__axiom_profiles)'
        \\
        \\# Environment commands - complete with environment names
        \\complete -c axiom -n '__fish_seen_subcommand_from activate env-destroy' -a '(__axiom_environments)'
        \\
        \\# Package commands - complete with package names
        \\complete -c axiom -n '__fish_seen_subcommand_from install remove info' -a '(__axiom_packages)'
        \\
        \\# Key commands - complete with key IDs
        \\complete -c axiom -n '__fish_seen_subcommand_from key-remove key-trust' -a '(__axiom_keys)'
        \\
        \\# Cache commands - complete with cache URLs
        \\complete -c axiom -n '__fish_seen_subcommand_from cache-remove' -a '(__axiom_caches)'
        \\
        \\# User profile commands - complete with user profile names
        \\complete -c axiom -n '__fish_seen_subcommand_from user-profile-show user-profile-update user-profile-delete user-resolve' -a '(__axiom_user_profiles)'
        \\
        \\# User environment commands - complete with user environment names
        \\complete -c axiom -n '__fish_seen_subcommand_from user-activate user-env-destroy' -a '(__axiom_user_environments)'
        \\
        \\# File completion for import, sign, verify, key-add, build
        \\complete -c axiom -n '__fish_seen_subcommand_from import sign verify key-add build' -F
        \\
        \\# Completions command
        \\complete -c axiom -n '__fish_seen_subcommand_from completions' -a 'bash zsh fish'
        \\
        \\# GC options
        \\complete -c axiom -n '__fish_seen_subcommand_from gc' -l dry-run -d 'Show what would be collected'
        \\complete -c axiom -n '__fish_seen_subcommand_from gc' -l force -d 'Force collection'
        \\
        \\# Cache-fetch options
        \\complete -c axiom -n '__fish_seen_subcommand_from cache-fetch' -l no-verify -d 'Skip signature verification'
        \\complete -c axiom -n '__fish_seen_subcommand_from cache-fetch' -l install -d 'Install after fetch'
        \\
        \\# Cache-clean options
        \\complete -c axiom -n '__fish_seen_subcommand_from cache-clean' -s f -l force -d 'Force cleanup'
        \\
        \\# Sign options
        \\complete -c axiom -n '__fish_seen_subcommand_from sign' -l key -d 'Key file to use' -F
        \\
        \\# Build options
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l jobs -d 'Number of parallel jobs'
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l no-test -d 'Skip test phase'
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l dry-run -d 'Show build plan only'
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l keep-sandbox -d 'Keep sandbox after build'
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l no-import -d 'Do not import result'
        \\complete -c axiom -n '__fish_seen_subcommand_from build' -l verbose -d 'Show detailed output'
        \\
    );
}
